Removed nightly ci and removed not needed things in pipelines

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -293,11 +293,11 @@ jobs:
       - name: Set file permissions
         run: chmod +x ${{ github.workspace }}/artifacts/crud-bench
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USER }}
-          password: ${{ secrets.DOCKER_TOKEN }}
+      # - name: Login to Docker Hub
+        # uses: docker/login-action@v3
+        # with:
+        #   username: ${{ secrets.DOCKER_USER }}
+        #   password: ${{ secrets.DOCKER_TOKEN }}
 
       - name: ${{ matrix.skipped || 'Benchmark processing' }}
         if: ${{ !matrix.enabled }}
@@ -311,32 +311,32 @@ jobs:
           docker container prune --force
           docker system prune --force
           # Clean up data directory
-          rm -rf /tmp/crud-bench
-          mkdir /tmp/crud-bench
-          chmod 777 /tmp/crud-bench
+          # rm -rf /tmp/crud-bench
+          # mkdir /tmp/crud-bench
+          # chmod 777 /tmp/crud-bench
           # Remove old results
           rm -f result*.json
           rm -f result*.csv
 
-      - name: Optimise system
-        if: ${{ matrix.enabled && ( github.event.inputs.datastore == 'all' || contains(matrix.name, github.event.inputs.datastore) || ( github.event.inputs.datastore == 'custom' && contains(github.event.inputs.custom, matrix.name) ) ) && (success() || failure()) }}
-        run: |
-          # Disable services
-          sudo systemctl stop unattended-upgrades
-          # Flush disk writes
-          sync
-          # Clear page tables
-          echo 1 | sudo tee /proc/sys/vm/compact_memory
-          # Drop memory caches
-          echo 3 | sudo tee /proc/sys/vm/drop_caches
-          # Disable Transparent Hugh Pages
-          echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
-          # Disable swap memory
-          sudo swapoff -a
-          # Increase max limits
-          ulimit -n 65536
-          ulimit -u unlimited
-          ulimit -l unlimited
+      # - name: Optimise system
+      #   if: ${{ matrix.enabled && ( github.event.inputs.datastore == 'all' || contains(matrix.name, github.event.inputs.datastore) || ( github.event.inputs.datastore == 'custom' && contains(github.event.inputs.custom, matrix.name) ) ) && (success() || failure()) }}
+      #   run: |
+      #     # Disable services
+      #     sudo systemctl stop unattended-upgrades
+      #     # Flush disk writes
+      #     sync
+      #     # Clear page tables
+      #     echo 1 | sudo tee /proc/sys/vm/compact_memory
+      #     # Drop memory caches
+      #     echo 3 | sudo tee /proc/sys/vm/drop_caches
+      #     # Disable Transparent Hugh Pages
+      #     echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
+      #     # Disable swap memory
+      #     sudo swapoff -a
+      #     # Increase max limits
+      #     ulimit -n 65536
+      #     ulimit -u unlimited
+      #     ulimit -l unlimited
 
       - name: Wait for system cool down
         if: ${{ matrix.enabled && ( github.event.inputs.datastore == 'all' || contains(matrix.name, github.event.inputs.datastore) || ( github.event.inputs.datastore == 'custom' && contains(github.event.inputs.custom, matrix.name) ) ) && (success() || failure()) }}
